name: CI/CD Pipeline

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./application_code   # 👈 change path here

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --include=dev   # fixed flag

      - name: Run lint
        run: npm run lint

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/nawy-task
          tags: |
            type=sha,format=short

      - name: Build Docker image
        run: docker build -t ${{ steps.meta.outputs.tags }} .

      - name: Add latest tag to the image
        run: docker tag ${{ steps.meta.outputs.tags }} ${{ secrets.DOCKER_USERNAME }}/nawy-task:latest

      - name: Push Docker images
        run: |
          docker push ${{ steps.meta.outputs.tags }}
          docker push ${{ secrets.DOCKER_USERNAME }}/nawy-task:latest